### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by thomascwells** [shanejorr/usincometaxes#14]
`./LICENSE` and `./LICENSE.md` reference different licenses. Should probably land on one for clarity as this effects what license is displayed on the GitHub repo page. I think the confusion might be arising from the DESCRIPTION file, here: https://github.com/shanejorr/usincometaxes/blob/main/DESCRIPTION#L11

**Comment by shanejorr** [comment]
Recreated licenses with `usethis::use_mit_license()` as per the [R Packages book, section 2.11](https://r-pkgs.org/whole-game.html?q=license#use_mit_license).  I visually inspected the LICENSE file and it looks as [section 2.11](https://r-pkgs.org/whole-game.html?q=license#use_mit_license) says it should look. 

I also checked everything against [dplyr's](https://github.com/tidyverse/dplyr) MIT license and the files do mirror each other.

**Comment by thomascwells** [comment]
Oh, my mistake! Thanks for double checking!
