### ISSUE TITLE
Updating WebAssembly files in the package

### ISSUE THREAD

**Issue by shanejorr** [shanejorr/usincometaxes#15]
Hello @thomascwells and @tmm1! I'm updating the documentation to reflect the wasm addition at this branch: https://github.com/shanejorr/usincometaxes/tree/update-wasm

The vignette referenced in #13 has been started: https://github.com/shanejorr/usincometaxes/blob/update-wasm/vignettes/interface-options.Rmd, but is not complete.

In creating the vignette, I thought of a potential downstream issue when using wasm. Assuming we keep the file updated in the package, people installing the package will have the most up to date files. But, as it stands now, people that have already installed the package cannot get the most updated JS / WebAssembly files when these files are updated without reinstalling the package. Additionally, there is no trigger to tell them the files are out of date.

I can see two possible solutions:

1. When the package loads, ping something (not sure yet what that would be) to see if the JS / WebAssembly files in the package version they are using are the most up to date (compared to the files that are in the current version of the package). If not, provide a message strongly suggesting that they reinstall the pacakge.
2. Redownload the files into a temporary directory the first time that the 'wasm' option is used in a session. Essentially, everytime the 'wasm' option is used, we would check to see if the JS and WASM files are in the temp directory and if not they will be downloaded.

The files download pretty quickly, so I would lean towards option 2. It seems more fool-proof. Of course, you now need an internet connection to use the package, but I don't think that is too large of a problem.

But, I wanted to get other thoughts if you all have any and make sure I'm understanding everything correctly.x

**Comment by tmm1** [comment]
I'm not very familiar with CRAN/R, but are you saying when users upgrade to a new version of the package the inst/ files won't update as well?

Or is there not the concept of upgrading and you can only reinstall the newest available?

As far as updating the js/wasm, the ETag can be used to detect if the hosted version has changed.

```
$ curl --head -v -o /dev/null http://taxsim.nber.org/taxsim35/taxsim.wasm 2>&1 | grep ETag
< ETag: "e13fd-5df631c73f435"

**Comment by shanejorr** [comment]
Thanks for the ETag. Checking that could be an easy solution as long as the files in the R package are update soon after the js/wasm file updates.

Regarding your question: The inst/ files will update when the package is updated / reinstalled. But, there certainly is not a concept of automatic updates. And, you do essentially update packages by simply reinstalling them. That said, it's easy to reinstall, its just one function call `install.package('usincometaxes)`. The previous command installs / reinstalls the package.

**Comment by thomascwells** [comment]
I think it's preferable to have the wasm version fixed to a specific
package version. As a user, I wouldn't want the wasm (and thus the
underlying code functionality) to change if I haven't done anything to
update the package.

Also, for folks like myself who use RStudio's `renv` package+workflow to
gain better control over package versions and dependencies, the expectation
is that a given version of a package will always perform the same no matter
when or where I install it. If we allow users to update the wasm without
updating the package, it breaks that reproducibility and environment
control.

**Comment by shanejorr** [comment]
Thanks @thomascwells the reproducibility angle makes perfect sense. Thanks for helping me think it through. We'll keep things as is and I will note these items in the documentation.

**Comment by thomascwells** [comment]
Sounds great! I'll take a stab at adding to, or reviewing documentation next time I get a chance.

Also, it doesn't seem like the tighter integration with the Fortran source will be available soon, and it's going to require some extensive testing, so I suggest going forward with CRAN submission as soon as you're ready.
