### ISSUE TITLE
Errors in marginal tax rate

### ISSUE THREAD

**Issue by mbarecon** [shanejorr/usincometaxes#18]
Here is example of a tax return:
# Checking for error
family_income <- data.frame(
  taxsimid = 1,
  state = 'CA',
  year = 2021,
  mstat = 'married, jointly',
  depx = 2,
  age1 = 10,
  age2 = 7,
  pwages = 120000, # primary wages
  swages = 30000, # spousal wages
  interface =  "http" #c("wasm", "ssh", "http")
)

family_taxes <- taxsim_calculate_taxes(
  .data = family_income,
  marginal_tax_rates = 'Wages',
  return_all_information = FALSE
)
The resulting frate = 83, which is impossible. There is no 83% tax bracket in the federal tax code. I obtained similar errors in other examples as well.

**Comment by shanejorr** [comment]
Thank you for noticing. I think the TAXSIM server changed something on the order of columns for output and tests did not catch it. I'm going to revamp things and make 'wasp' the only interface. That way, changes to the TAXSIM server won't catch me by suprise.

**Comment by shanejorr** [comment]
I updated the package to where users can no longer use ssh or http to send data to the TAXSIM server. All operations must be completed using the 'wasm' interface. This will stabalize things and ensure that changes to the TAXSIM server don't introduce issues.
