### ISSUE TITLE
Error in taxsim calculation

### ISSUE THREAD

**Issue by simonessigaberg** [shanejorr/usincometaxes#20]
Hello! I ran the following example code in Linux:
```
library(dplyr)
library(knitr)
library(usincometaxes)

family_income <- data.frame(
  taxsimid = c(1, 2),
  state = c('North Carolina', 'NY'),
  year = c(2015, 2020),
  mstat = c('married, jointly', 'single'),
  pwages = c(50000, 100000), # primary wages
  page = c(26, 36) # primary age
)

family_taxes <- taxsim_calculate_taxes(
  .data = family_income,
  marginal_tax_rates = 'Wages',
  return_all_information = FALSE
)
```

I get the following error:
> Error: There was a problem in calculating the taxes. Please check the format of your data.
> If the problem persists, you can try manually uploading the data to TAXSIM as an avenue of troubleshooting.
> See the following address for more information: https://www.shaneorr.io/r/usincometaxes/articles/send-data-to-taxsim.html

When I run the code on macOS, the console crashes with the error:
> Process finished with exit code 133 (interrupted by signal 5:SIGTRAP).

Please let me know if you have any guidance on this.

Thank you!

**Comment by shanejorr** [comment]
Hi - Unfortunately, I am not able to recreate the issue in Mac or Linux. Could you try running the following, as it could help narrow down where the problem is occuring:

```
library(usincometaxes)

family_income <- data.frame(
  taxsimid = c(1, 2),
  state = c('North Carolina', 'NY'),
  year = c(2015, 2020),
  mstat = c('married, jointly', 'single'),
  pwages = c(50000, 100000), # primary wages
  page = c(26, 36) # primary age
)

create_dataset_for_taxsim(family_income)
```

Also, which IDE are you using? I ask because the only information I could find on the error message is [this one from users who use PyCharm](https://youtrack.jetbrains.com/issue/R-1506/Unexpected-Termination-of-R-with-Exit-Code-133-when-Loading-Required-Packages-in-PyCharm-R-Project-on-macOS-13.4-Ventura).

**Comment by simonessigaberg** [comment]
Thanks--I've done a bit more experimentation.

The function create_dataset_for_taxsim() works for me regardless of operating system / IDE. 

The function taxsim_calculate_taxes() is only working for certain combinations of operating systems / IDEs. 
macOS and PyCharm: does not work
macOS and RStudio: works
macOS and R: works
Linux and R: does not work

Is there any additional information I can provide?

**Comment by shanejorr** [comment]
My suspicion is that it has something to do with the use of WebAssembly. Can you try the following and see where the error occurs?

```
library(usincometaxes)

family_income <- data.frame(
  taxsimid = c(1, 2),
  state = c('North Carolina', 'NY'),
  year = c(2015, 2020),
  mstat = c('married, jointly', 'single'),
  pwages = c(50000, 100000), # primary wages
  page = c(26, 36) # primary age
)

.data <- create_dataset_for_taxsim(family_income)

# connect to js and wasm files
wasm_path   <- system.file("taxsim/taxsim.wasm", package = "usincometaxes")
js_path     <- system.file("taxsim/taxsim.js",    package = "usincometaxes")
wasm_binary <- readBin(wasm_path, raw(), file.info(wasm_path)$size)

# convert input data to string
data_string <- vroom::vroom_format(.data, delim = ",", eol = "\\n")

# load the V8 context
ctx <- V8::v8()
ctx$assign("wasmBinary", wasm_binary)
ctx$source(js_path)

response_text <- ctx$call("taxsim",
                          V8::JS(paste0("'", data_string, "'")),
                          V8::JS("{wasmBinary}"),
                          await = TRUE)

from_taxsim <- tibble::tibble(
  utils::read.table(text = response_text,
                    header = T,
                    sep = ","))

print(from_taxsim)
```

**Comment by simonessigaberg** [comment]
The error occurs at
```
ctx <- V8::v8()
```

**Comment by shanejorr** [comment]
Thanks for that. It does look like it is an issue with the `v8` package and WASM. I looked into fixed and I could not find anything. So, I am not sure I know of a fix with `v8`, but hopefully you can use one of the systems that does work.

**Comment by simonessigaberg** [comment]
Sounds good--thank you for your help!
