### ISSUE TITLE
Enhancement: allow the R package to also connect with a local version of Taxsim35

### ISSUE THREAD

**Issue by AlexPars** [shanejorr/usincometaxes#21]
It would be very useful if you can allow the user (of usincometaxes) the option of either uploading the data to the NBER server, or to connect with a local version of Taxsim35, given that Taxsim35 can be installed locally
https://taxsim.nber.org/taxsim35/low-level-local.html

**Comment by thomascwells** [comment]
Shane can correct me if I'm wrong, but I believe the R package [now only uses the WASM](https://www.shaneorr.io/r/usincometaxes/news/) interface of Taxsim35 to perform calculations. This means data is not uploaded to NBER and all calculations are performed locally on the user's machine. 

Accessing Taxsim through the [WASM method](https://www.shaneorr.io/r/usincometaxes/articles/wasm) is probably easier for most users and is certainly more cross-platform friendly than user-installed binaries. 

Is there a particular use case you have in mind that isn't addressed via the locally-run WASM method? 

If you're curious, the R code for the WASM interface can be found here (this is where the "magic" happens anyway):  
https://github.com/shanejorr/usincometaxes/blob/439e83e2991d15c6696e82016fe8a3001bf20e52/R/utils_connect_server.R

**Comment by AlexPars** [comment]
Thank you.

I was not fully clear what exactly happens, based on reading 
https://cran.r-project.org/web/packages/usincometaxes/vignettes/wasm.html

So the user needs to obtain taxsim.f from NBER, and taxsim.js from https://github.com/tmm1/taxsim.js

**Comment by thomascwells** [comment]
It's actually even easier than that: the R package comes bundled with all the necessary files. The user doesn't need to download anything extra. 

If you've been able to install the package and run any code (like the examples in the vignette), you're already using the WASM interface.

Is the package working for you with any sample code?

**Comment by shanejorr** [comment]
I will close issue based on Thomas's instructions.
