### ISSUE TITLE
Connection to TAXSIM server failed

### ISSUE THREAD

**Issue by m-riviere** [shanejorr/usincometaxes#3]
Hi,

I'm running into an error when trying to run your example code while it was working a few days ago. The connection to the TAXSIM server seems to be failing. Here is the error: 
"All required columns are present and the data is in the proper format!
Connecting to TAXSIM server via ftp ...
Connecting to TAXSIM server via ssh on port 443...
ssh: connect to host taxsimssh.nber.org port 443: Connection timed out
Connecting to TAXSIM server via ssh on port 80...
ssh: connect to host taxsimssh.nber.org port 80: Connection timed out
Connecting to TAXSIM server via ssh on port 20...
ssh: connect to host taxsimssh.nber.org port 20: Connection timed out
Error: Could not connect to TAXSIM server via ftp or ssh"

I am using a windows computer if this could help.

Thank you for your help.

**Comment by shanejorr** [comment]
Thank you for the heads up. I tried on a Windows machine and I am also unable to connect to the TAXSIM server. NBER recently updated TAXSIM to version 35 (http://users.nber.org/~taxsim/taxsim35/). I am in the process of converting everything to version 35, which connects to a different server. Hopefully, I am able to complete this within the next two weeks. I hope that things will be back to working when I convert to TAXSIM 35.

I will keep this open and respond when I convert to TAXSIM 35, so you can see if this solves the issue.

**Comment by shanejorr** [comment]
I updated the package so that it now works with TAXSIM 35 (http://users.nber.org/~taxsim/taxsim35/). Everything should be working now,

**Comment by m-riviere** [comment]
Thank you very much!
