### ISSUE TITLE
Internal function `taxsim_cols()` does not contain all current cols in TAXSIM

### ISSUE THREAD

**Issue by thomascwells** [shanejorr/usincometaxes#6]
I don't know how many columns are missing from the internal `taxsim_cols()` function, but at least `psemp` (primary self employment income) is missing. 

I think the complete list can be gleaned by leaving all values default and pressing "calculate this single taxpayer" on this page: https://taxsim.nber.org/taxsim35/, then copying the 2nd row with the input data.

This may be the complete list: 
```
mtr=85,idtl=5,opt1=0,taxsim=1,year=2006,state=0,mstat=2,page=0,sage=0,depx=0,age1=0,age2=0,age3=0,pwages=0,swages=0,psemp=0,ssemp=0,divide=0,intrec=0,stcg=0,ltcg=0,otherp=0,nonpro=0,pensio=0,gssi=0,pui=0,sui=0,transf=0,rentpa=0,propta=0,otheri=0,childc=0,mortga=0,scorp=0,pbusin=0,pprofi=0,sbusin=0,sprofi=0
``` 

I have an in-progress branch to fix this, here (still testing).
https://github.com/thomascwells/usincometaxes/tree/fix-taxsim_cols-function

**Comment by shanejorr** [comment]
Thank you again for identifying the issue. I will close this in lieu of the pull request.
